<?php

function multipass_help($path, $arg) {
  switch ($path) {
    case 'admin/help#multipass':
      return '<p>' . t('The Multipass Module lets you easily generate a Multipass link in any one of your theme templates') . '</p>';
  }
}

function multipass_theme() {
  return array(
    'multipass' => array(
      'arguments' => array('link' => NULL, 'sso_key' => NULL, 'key' => NULL, 'anchor_text' => "Support"),
    ),
  );
}
/**
 * Generates the Tender API Key
 *
 * @param string $link Your tender link http://yourapp.tender.com
 * @param string $sso_key Your Tender site Key
 * @param string $key Your Tender SSO API Key
 * @param string $text The visible text between the anchor element
 * @return void
 * @author Kenny Meyers
 */
function theme_multipass($link, $sso_key, $key, $anchor_text="Support") {
  global $user;

  //Checks to see if a tender link was even entered
  if (!$link = str_replace("http://", "", $link)) { 
    drupal_set_message( t("You haven't entered your Tender App URL"), "error"); 
    return;
  }
  
  if ($key == "") {
    drupal_set_message( t("You haven't entered your Tender Key"));
    return;
  }
  elseif ($sso_key=="") {
    drupal_set_message( t("You haven't entered your SSO API Key"));
    return;
  }
  // Checks to see if the user is logged in if not just returns the link
  if (0 == $user->uid || "" == $user->uid) {
    echo  '<a href="http://' . $link . '">' . $anchor_text . '</a>';
    return;
  }
  
  //Is the user's email setup?
  if ($user->mail == "") {
    drupal_set_message( t("You must be logged in for support"), "error");
    return;
  }

  $tender_params = array(
    'unique_id' => $user->uid,
    'name'      => $user->name,
    'email'     => $user->mail,
    'sso_key'   => $sso_key,
    'site_key'  => $key,
    'expires'   => date("Y-m-d H:i:s", strtotime("+30 minutes")),
    'trusted'   => TRUE,
  );
  
  //Finally generate the Tender URL
  echo '<a href="http://' . $link  . _getTenderLink($tender_params) . '">' . $anchor_text . '</a>';
}

/**
 * Generates a Tender API link, accepting parameters and doing all the
 * hashing, security-ing, and modify-ing.
 *
 * @param array $params 
 * @return void
 */
function _getTenderLink($params) {
  $hash= hash('sha1', $params['sso_key'] . $params['site_key'], TRUE);
  
  //Remove the API & SSO Key from the Params
  unset($params['sso_key']);
  unset($params['site_key']); 
  
  $saltedHash = substr($hash, 0, 16);
  
  $iv= "OpenSSL for Ruby";

  $data = json_encode($params);
  
  for ($i = 0; $i < 16; $i++) {
      $data[$i] = $data[$i] ^ $iv[$i];
  }

  $pad = 16 - (strlen($data) % 16);
  $data = $data . str_repeat(chr($pad), $pad);
  $cipher = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', 'cbc', '');
  mcrypt_generic_init($cipher, $saltedHash, $iv);
  $encryptedData = mcrypt_generic($cipher, $data);
  mcrypt_generic_deinit($cipher);

  $multipass = urlencode(base64_encode($encryptedData));
  
  return "?sso={$multipass}";
}